-- MySQL Script generated by MySQL Workbench
-- Monday 25 June 2018 04:36:24 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`periods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`periods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `period` VARCHAR(45) NULL,
  `order` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dynasties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dynasties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dynasty` VARCHAR(45) NULL,
  `polity` VARCHAR(45) NULL,
  `order` INT(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `order_UNIQUE` (`order` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rulers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rulers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ruler` VARCHAR(45) NULL,
  `order` VARCHAR(45) NULL,
  `period_id` INT(11) NULL,
  `dynasty_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `order_UNIQUE` (`order` ASC),
  INDEX `fk_rulers_1_idx` (`period_id` ASC),
  INDEX `fk_rulers_2_idx` (`dynasty_id` ASC),
  CONSTRAINT `fk_rulers_1`
    FOREIGN KEY (`period_id`)
    REFERENCES `mydb`.`periods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rulers_2`
    FOREIGN KEY (`dynasty_id`)
    REFERENCES `mydb`.`dynasties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`year_names`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`year_names` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `period_id` INT(11) NULL,
  `ruler_id` INT(11) NULL,
  `dynasty_id` INT(11) NULL,
  `year_number` VARCHAR(45) NULL,
  `type` ENUM('year', 'eponym') NULL,
  `order` INT(11) NULL,
  `year_and_eponym` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_year_names_1_idx` (`period_id` ASC),
  INDEX `fk_year_names_2_idx` (`ruler_id` ASC),
  INDEX `fk_year_names_3_idx` (`dynasty_id` ASC),
  UNIQUE INDEX `order_UNIQUE` (`order` ASC),
  CONSTRAINT `fk_year_names_1`
    FOREIGN KEY (`period_id`)
    REFERENCES `mydb`.`periods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_year_names_2`
    FOREIGN KEY (`ruler_id`)
    REFERENCES `mydb`.`rulers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_year_names_3`
    FOREIGN KEY (`dynasty_id`)
    REFERENCES `mydb`.`dynasties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`month_names`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`month_names` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `composite_month_name` VARCHAR(45) NULL,
  `type` ENUM('with_date', 'without_date') NULL,
  `order` INT(11) NULL,
  `month_number` VARCHAR(10) NULL,
  `ruler_id` INT(11) NULL,
  `year_name_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_month_names_1_idx` (`ruler_id` ASC),
  INDEX `fk_month_names_2_idx` (`year_name_id` ASC),
  CONSTRAINT `fk_month_names_1`
    FOREIGN KEY (`ruler_id`)
    REFERENCES `mydb`.`rulers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_month_names_2`
    FOREIGN KEY (`year_name_id`)
    REFERENCES `mydb`.`year_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NULL,
  `type` ENUM('start_date', 'end_date') NULL,
  `order` INT(11) NULL,
  `month_name_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dates_1_idx` (`month_name_id` ASC),
  CONSTRAINT `fk_dates_1`
    FOREIGN KEY (`month_name_id`)
    REFERENCES `mydb`.`month_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
