-- MySQL Script generated by MySQL Workbench
-- Sun Sep 23 01:35:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveniences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveniences` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `google_earth_collection` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `google_earth_provenience` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `geo_coordinates` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `provenience` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dynasties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dynasties` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `polity` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `dynasty` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `order` INT(2) NULL,
  `provenience_id` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dynasties_1_idx` (`provenience_id` ASC) VISIBLE,
  CONSTRAINT `fk_dynasties_1`
    FOREIGN KEY (`provenience_id`)
    REFERENCES `mydb`.`proveniences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`years`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`years` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `year` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `order` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`periods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`periods` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `period` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `order` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`year_names`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`year_names` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `year_number` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `year_and_eponym` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `type` ENUM('year', 'eponym') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `order` INT(2) NULL DEFAULT NULL,
  `year_id` INT(10) NULL DEFAULT NULL,
  `period_id` INT(10) NULL DEFAULT NULL,
  `dynasty_id` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_year_and_eponym_names_1_idx` (`year_id` ASC) VISIBLE,
  INDEX `fk_year_names_1_idx` (`period_id` ASC) VISIBLE,
  INDEX `fk_year_names_2_idx` (`dynasty_id` ASC) VISIBLE,
  CONSTRAINT `fk_year_and_eponym_names_1`
    FOREIGN KEY (`year_id`)
    REFERENCES `mydb`.`years` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_year_names_1`
    FOREIGN KEY (`period_id`)
    REFERENCES `mydb`.`periods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_year_names_2`
    FOREIGN KEY (`dynasty_id`)
    REFERENCES `mydb`.`dynasties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rulers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rulers` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `ruler` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `order` INT(2) NULL DEFAULT NULL,
  `period_id` INT(10) NULL DEFAULT NULL,
  `dynasty_id` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rulers_1_idx` (`period_id` ASC) VISIBLE,
  INDEX `fk_rulers_2_idx` (`dynasty_id` ASC) VISIBLE,
  CONSTRAINT `fk_rulers_1`
    FOREIGN KEY (`period_id`)
    REFERENCES `mydb`.`periods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rulers_2`
    FOREIGN KEY (`dynasty_id`)
    REFERENCES `mydb`.`dynasties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`months`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`months` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `composite_month_name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `order` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`month_names`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`month_names` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `month_number` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `order` INT(2) NULL DEFAULT NULL,
  `type` ENUM('ruler', 'place') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `month_id` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_month_names_3_idx` (`month_id` ASC) VISIBLE,
  CONSTRAINT `fk_month_names_3`
    FOREIGN KEY (`month_id`)
    REFERENCES `mydb`.`months` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dates` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `day_number` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `date_remarks` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  `order` INT(2) NULL DEFAULT NULL,
  `is_uncertain` ENUM('yes', 'no') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artifacts_dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artifacts_dates` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `date_created_accuracy` INT(10) NULL DEFAULT NULL,
  `artifact_id` INT(10) NULL DEFAULT NULL,
  `ruler_id` INT(10) NULL DEFAULT NULL,
  `year_name_id` INT(10) NULL DEFAULT NULL,
  `month_name_id` INT(10) NULL DEFAULT NULL,
  `date_id` INT(10) NULL DEFAULT NULL,
  `date_type` ENUM('origin', 'referenced', 'accounting_period_start', 'accounting_period_end') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_artifacts_dates_3_idx` (`artifact_id` ASC) VISIBLE,
  INDEX `fk_artifacts_dates_4_idx` (`ruler_id` ASC) VISIBLE,
  INDEX `fk_artifacts_dates_5_idx` (`year_name_id` ASC) VISIBLE,
  INDEX `fk_artifacts_dates_6_idx` (`month_name_id` ASC) VISIBLE,
  INDEX `fk_artifacts_dates_7_idx` (`date_id` ASC) VISIBLE,
  CONSTRAINT `fk_artifacts_dates_3`
    FOREIGN KEY (`artifact_id`)
    REFERENCES `mydb`.`artifacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artifacts_dates_4`
    FOREIGN KEY (`ruler_id`)
    REFERENCES `mydb`.`rulers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artifacts_dates_5`
    FOREIGN KEY (`year_name_id`)
    REFERENCES `mydb`.`year_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artifacts_dates_6`
    FOREIGN KEY (`month_name_id`)
    REFERENCES `mydb`.`month_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artifacts_dates_7`
    FOREIGN KEY (`date_id`)
    REFERENCES `mydb`.`dates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artifacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artifacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `artifacts_dates_id` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_artifacts_1_idx` (`artifacts_dates_id` ASC) VISIBLE,
  CONSTRAINT `fk_artifacts_1`
    FOREIGN KEY (`artifacts_dates_id`)
    REFERENCES `mydb`.`artifacts_dates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
