-- MySQL Script generated by MySQL Workbench
-- Saturday 28 July 2018 02:21:53 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveniences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveniences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `google_earth_collection` VARCHAR(255) NULL DEFAULT NULL,
  `google_earth_provenience` VARCHAR(255) NULL DEFAULT NULL,
  `provenience` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dynasties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dynasties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `polity` VARCHAR(45) NULL DEFAULT NULL,
  `dynasty` VARCHAR(45) NULL DEFAULT NULL,
  `order` INT(2) NULL,
  `provenience_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dynasties_1_idx` (`provenience_id` ASC),
  UNIQUE INDEX `d_order_UNIQUE` (`order` ASC),
  CONSTRAINT `fk_dynasties_1`
    FOREIGN KEY (`provenience_id`)
    REFERENCES `mydb`.`proveniences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`years`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`years` (
  `id` INT NOT NULL,
  `year` VARCHAR(45) NULL,
  `order` INT(2) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `order_UNIQUE` (`order` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`periods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`periods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `period` VARCHAR(80) NOT NULL,
  `order` INT(2) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `order_UNIQUE` (`order` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`year_names`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`year_names` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year_number` VARCHAR(45) NULL,
  `year_and_eponym` VARCHAR(255) NULL DEFAULT NULL,
  `type` ENUM('year', 'eponym') NULL,
  `order` INT(2) NULL,
  `year_id` INT(11) NULL,
  `period_id` INT(11) NULL,
  `dynasty_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_year_and_eponym_names_1_idx` (`year_id` ASC),
  UNIQUE INDEX `order_UNIQUE` (`order` ASC),
  INDEX `fk_year_names_1_idx` (`period_id` ASC),
  INDEX `fk_year_names_2_idx` (`dynasty_id` ASC),
  CONSTRAINT `fk_year_and_eponym_names_1`
    FOREIGN KEY (`year_id`)
    REFERENCES `mydb`.`years` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_year_names_1`
    FOREIGN KEY (`period_id`)
    REFERENCES `mydb`.`periods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_year_names_2`
    FOREIGN KEY (`dynasty_id`)
    REFERENCES `mydb`.`dynasties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rulers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rulers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ruler` VARCHAR(45) NULL DEFAULT NULL,
  `order` INT(2) NULL,
  `period_id` INT(11) NULL,
  `dynasty_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rulers_1_idx` (`period_id` ASC),
  UNIQUE INDEX `r_order_UNIQUE` (`order` ASC),
  INDEX `fk_rulers_2_idx` (`dynasty_id` ASC),
  CONSTRAINT `fk_rulers_1`
    FOREIGN KEY (`period_id`)
    REFERENCES `mydb`.`periods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rulers_2`
    FOREIGN KEY (`dynasty_id`)
    REFERENCES `mydb`.`dynasties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`months`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`months` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `composite_month_name` VARCHAR(100) NULL,
  `order` INT(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`month_names`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`month_names` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order` INT(2) NULL,
  `month_number` VARCHAR(45) NULL,
  `type` ENUM('ruler', 'place') NULL,
  `month_id` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_month_names_3_idx` (`month_id` ASC),
  CONSTRAINT `fk_month_names_3`
    FOREIGN KEY (`month_id`)
    REFERENCES `mydb`.`months` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day_number` VARCHAR(45) NULL,
  `date_remarks` VARCHAR(45) NULL,
  `order` INT(5) NULL,
  `period_id` INT(11) NULL,
  `start_dynasty` INT(10) NULL,
  `start_month` INT(10) NULL,
  `start_ruler` INT(10) NULL,
  `start_year` INT(10) NULL,
  `end_dynasty` INT(10) NULL,
  `end_month` INT(10) NULL,
  `end_ruler` INT(10) NULL,
  `end_year` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dates_4_idx` (`period_id` ASC),
  INDEX `fk_dates_1_idx` (`start_dynasty` ASC),
  INDEX `fk_dates_2_idx` (`end_dynasty` ASC),
  INDEX `fk_dates_3_idx` (`start_month` ASC),
  INDEX `fk_dates_6_idx` (`end_month` ASC),
  INDEX `fk_dates_7_idx` (`start_ruler` ASC),
  INDEX `fk_dates_8_idx` (`end_ruler` ASC),
  INDEX `fk_dates_9_idx` (`start_year` ASC),
  INDEX `fk_dates_10_idx` (`end_year` ASC),
  CONSTRAINT `fk_dates_4`
    FOREIGN KEY (`period_id`)
    REFERENCES `mydb`.`periods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dates_1`
    FOREIGN KEY (`start_dynasty`)
    REFERENCES `mydb`.`dynasties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dates_2`
    FOREIGN KEY (`end_dynasty`)
    REFERENCES `mydb`.`dynasties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dates_3`
    FOREIGN KEY (`start_month`)
    REFERENCES `mydb`.`month_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dates_6`
    FOREIGN KEY (`end_month`)
    REFERENCES `mydb`.`month_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dates_7`
    FOREIGN KEY (`start_ruler`)
    REFERENCES `mydb`.`rulers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dates_8`
    FOREIGN KEY (`end_ruler`)
    REFERENCES `mydb`.`rulers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dates_9`
    FOREIGN KEY (`start_year`)
    REFERENCES `mydb`.`year_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dates_10`
    FOREIGN KEY (`end_year`)
    REFERENCES `mydb`.`year_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artifacts_dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artifacts_dates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accounting_period_start` INT(10) NULL,
  `accounting_period_end` INT(10) NULL,
  `date_created_accuracy` INT(10) NULL,
  `artifact_id` INT(10) NULL,
  `ruler_id` INT(10) NULL,
  `year_id` INT(10) NULL,
  `month_name_id` INT(10) NULL,
  `date_id` INT(10) NULL,
  `date_type` ENUM('origin', 'referenced', 'accounting_period_start', 'accounting_period_end') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_artifacts_dates_1_idx` (`accounting_period_start` ASC),
  INDEX `fk_artifacts_dates_2_idx` (`accounting_period_end` ASC),
  INDEX `fk_artifacts_dates_3_idx` (`artifact_id` ASC),
  INDEX `fk_artifacts_dates_4_idx` (`ruler_id` ASC),
  INDEX `fk_artifacts_dates_5_idx` (`year_id` ASC),
  INDEX `fk_artifacts_dates_6_idx` (`month_name_id` ASC),
  INDEX `fk_artifacts_dates_7_idx` (`date_id` ASC),
  CONSTRAINT `fk_artifacts_dates_1`
    FOREIGN KEY (`accounting_period_start`)
    REFERENCES `mydb`.`dates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artifacts_dates_2`
    FOREIGN KEY (`accounting_period_end`)
    REFERENCES `mydb`.`dates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artifacts_dates_3`
    FOREIGN KEY (`artifact_id`)
    REFERENCES `mydb`.`artifacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artifacts_dates_4`
    FOREIGN KEY (`ruler_id`)
    REFERENCES `mydb`.`rulers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artifacts_dates_5`
    FOREIGN KEY (`year_id`)
    REFERENCES `mydb`.`year_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artifacts_dates_6`
    FOREIGN KEY (`month_name_id`)
    REFERENCES `mydb`.`month_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artifacts_dates_7`
    FOREIGN KEY (`date_id`)
    REFERENCES `mydb`.`dates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artifacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artifacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `artifacts_dates_id` INT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_artifacts_1_idx` (`artifacts_dates_id` ASC),
  CONSTRAINT `fk_artifacts_1`
    FOREIGN KEY (`artifacts_dates_id`)
    REFERENCES `mydb`.`artifacts_dates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
